subgraphs/venus/README.md

Add README to describe venus subgraph

Add venus subgraph readme

---

subgraphs/venus-governance/config/mainnet.json

Update governor Alpha start block to the block where it was deployed

Update governor alpha start block

---

subgraphs/venus/src/mappings/markets.ts

This PR brings over fixes from the original venus-subgraph repo to the new monorepo

Check reverted calls zero values

---

subgraphs/venus-governance/src/operations/create.ts

Fix index execute proposal

---

README.md

Adds information about how to query and reproduce indexing errors

add debugging info for fixing indexing errors

---

Dockerfile.deploy
subgraphs/venus/package.json

Add a deploy container to deploy the subgraphs from Jenkins

Add deploy container

---

README.md
subgraphs/isolated-pools/config/local.json
subgraphs/isolated-pools/package.json

Update readme for running integration tests 
Run local tests on bsc network
Remove staging url from testnet deployment

Minor updates

---

subgraphs/isolated-pools/subgraph-client/index.ts
subgraphs/isolated-pools/template.yaml
subgraphs/isolated-pools/tests/integration/pool.ts
subgraphs/isolated-pools/tests/integration/poolRegistry.ts
subgraphs/isolated-pools/tests/integration/queries/marketActionsQuery.graphql

[VEN-501](https://jira.toolsfdg.net/browse/VEN-501)
[VEN-583](https://jira.toolsfdg.net/browse/VEN-583)
Added tests for:
- NewBorrowCap
- NewPriceOracle
- MarketActionPaused
- NewMinLiquidatableCollateral
- NewCloseFactor
- NewLiquidationIncentive
- Asserting accountVTokenTransaction ID formats
Removed:
- PoolActionPaused

[VEN-501][VEN-583] Integration tests for all Pool events

---

subgraphs/isolated-pools/config/testnet.json

Updates the subgraph with the latest deployment addresses on testnet.

feat: updated tesnet addresses for latest deployment

---

subgraphs/isolated-pools/config/testnet.json
subgraphs/isolated-pools/package.json

Updates values for deploying to our testnet node. Documentation added to notion as well

ci: update testnet deployment values

---

subgraphs/isolated-pools/schema.graphql
subgraphs/isolated-pools/src/constants/index.ts
subgraphs/isolated-pools/src/mappings/vToken.ts
subgraphs/isolated-pools/src/operations/create.ts
subgraphs/isolated-pools/tests/VToken/index.test.ts
subgraphs/isolated-pools/tests/VToken/mocks.ts
subgraphs/isolated-pools/tests/integration/queries/marketByIdQuery.graphql
subgraphs/isolated-pools/tests/integration/queries/marketsQuery.graphql
subgraphs/isolated-pools/tests/integration/vTokens.ts

VEN-838
- Added `supplierCount` to Market
- Added `borrowerCount` to Market
- Added unit and integration tests for the corresponding logic

[VEN-838] Added count of suppliers and borrowers to market

---

subgraphs/isolated-pools/src/mappings/vToken.ts
subgraphs/isolated-pools/template.yaml
subgraphs/isolated-pools/tests/VToken/index.test.ts

This PR removes the `NewComptroller` event as it won't be indexed anymore.

refactor: removed NewComptroller event

---

subgraphs/isolated-pools/config/testnet.json
subgraphs/isolated-pools/package.json

Update testnet config  and command to latest testnet deployment

Update testnet config deployment

---

subgraphs/isolated-pools/template.yaml

Added PriceOracle ABI to the Pool template.

fix: added PriceOracle ABI to Pool

---

subgraphs/isolated-pools/config/testnet.json
subgraphs/venus-governance/config/testnet.json

- Updated testnet addresses to be in sync with https://github.com/VenusProtocol/isolated-pools/pull/168

feat: updated testnet addresses according to latest deployment

---

subgraphs/isolated-pools/config/local.json
subgraphs/isolated-pools/schema.graphql
subgraphs/isolated-pools/src/mappings/pool.ts
subgraphs/isolated-pools/src/operations/getOrCreate.ts
subgraphs/isolated-pools/src/operations/update.ts
subgraphs/isolated-pools/subgraph-client/index.ts
subgraphs/isolated-pools/tests/integration/pool.ts
subgraphs/isolated-pools/tests/integration/queries/accountTransactionsByAccountId.graphql
subgraphs/isolated-pools/tests/integration/queries/accountVTokenByAccount.graphql
subgraphs/isolated-pools/tests/integration/queries/accountVTokenByAccountAndMarket.graphql

- Adjusted Pool integration tests to be according to isolated-pools v0.0.18
- Fixed a bug where the AccountVTokenTransaction wouldn't get properly linked to its corresponding AccountVToken
- Added useful queries to retrieve AccountVToken related data

fix: fixed Pool events integration tests

---

.github/workflows/ci.yaml

- Removed `set git config` steps from our CI workflow

ci: removed set git config sections

---

subgraphs/isolated-pools/src/operations/updateOrCreate.ts

- enteredMarket would not get updated for pre-existing accountVToken objects, this PR fixes it.

fix: properly update accountVToken.enteredMarket

---

subgraphs/isolated-pools/config/testnet.json

Updated addresses with values from https://github.com/VenusProtocol/isolated-pools/pull/185

feat: updated testnet addresses with new deployment values

---

package.json
subgraphs/isolated-pools/template.yaml
subgraphs/isolated-pools/tests/VToken/mocks.ts
yarn.lock

- Bumped isolated pools package to 0.1.0-develop.3
- Updated NewAccessControlManager signature

feat: bumped isolated pools dep to 0.1.0-develop.3

---

package.json
subgraphs/isolated-pools/config/mainnet.json
subgraphs/isolated-pools/config/testnet.json
subgraphs/isolated-pools/schema.graphql
subgraphs/isolated-pools/src/constants/index.ts
subgraphs/isolated-pools/src/operations/create.ts
subgraphs/isolated-pools/src/operations/update.ts
subgraphs/isolated-pools/template.yaml
subgraphs/isolated-pools/tests/PoolRegistry/index.test.ts
subgraphs/isolated-pools/tests/VToken/mocks.ts
subgraphs/isolated-pools/tests/integration/poolRegistry.ts
subgraphs/isolated-pools/tests/integration/queries/poolsQuery.graphql
subgraphs/venus-governance/template.yaml
yarn.lock

Updated isolated pools subgraph to be use package 1.0.0 and added mainnet deployment/addresses

Bump @venusprotocol/isolated-pools and add mainnet addresses

---

subgraphs/isolated-pools/src/operations/update.ts

- Tries calling `supplyRatePerBlock`, so we fallback to 0 if there is an error

fix: fallback to 0 if supplyRatePerBlock reverts

---

subgraphs/isolated-pools/src/constants/index.ts
subgraphs/isolated-pools/src/operations/update.ts
subgraphs/isolated-pools/src/utilities/getTokenPriceInUsd.ts
subgraphs/isolated-pools/src/utilities/index.ts
subgraphs/isolated-pools/src/utilities/valueOrBigIntZeroIfReverted.ts
subgraphs/isolated-pools/src/utilities/valueOrNotAvailableIntIfReverted.ts

- Added function `valueOrBigIntZeroIfReverted`, to avoid repeading if blocks when checking if a call reverted

refactor: use function valueOrBigIntZeroIfReverted

---

subgraphs/isolated-pools/schema.graphql

Remove PoolRegistry entity because it isn't used

refactor: remove unused pool registry entity

---

subgraphs/isolated-pools/package.json

fix: update sepolia deploy command

---

subgraphs/venus/template.yaml

Use the correct handler for the MintBehalf event

fix: use mintbehalf handler for mintBehalf

---

subgraphs/venus/src/mappings/vToken.ts
subgraphs/venus/template.yaml
subgraphs/venus/tests/VToken/events.ts
subgraphs/venus/tests/VToken/index.test.ts

Adds missing new RepayBorrow event signature
Fixes clashes when trying to access the VToken abi in creating markets

Add missing updated repay borrow event

---

subgraphs/venus/schema.graphql
subgraphs/venus/src/constants/index.ts
subgraphs/venus/src/mappings/comptroller.ts
subgraphs/venus/src/mappings/vToken.ts
subgraphs/venus/src/operations/create.ts
subgraphs/venus/src/operations/getOrCreate.ts

Consolidate transactions to a single entity.
Remove AccountvTokenTransaction which was a duplicate of transactions.

refactor: consolidate transactions to a single entity

---

subgraphs/isolated-pools/schema.graphql
subgraphs/isolated-pools/src/operations/getOrCreate.ts
subgraphs/isolated-pools/src/operations/update.ts
subgraphs/isolated-pools/tests/VToken/index.test.ts
subgraphs/isolated-pools/tests/integration/pool.ts
subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
subgraphs/isolated-pools/tests/integration/queries/accountVTokenByAccount.graphql
subgraphs/isolated-pools/tests/integration/queries/accountVTokenByAccountAndMarket.graphql
subgraphs/isolated-pools/tests/integration/queries/accountVTokens.graphql

Explicitly label supply balance as in vTokens

refactor: explicitly label supply balance as vtokens

---

subgraphs/isolated-pools/schema.graphql
subgraphs/isolated-pools/src/mappings/poolRegistry.ts
subgraphs/isolated-pools/src/operations/create.ts
subgraphs/isolated-pools/src/operations/get.ts
subgraphs/isolated-pools/src/operations/getOrCreate.ts
subgraphs/isolated-pools/src/operations/updateOrCreate.ts
subgraphs/isolated-pools/src/utilities/ids.ts
subgraphs/isolated-pools/template.yaml
subgraphs/isolated-pools/tests/Pool/index.test.ts
subgraphs/isolated-pools/tests/RewardsDistributor/index.test.ts
subgraphs/isolated-pools/tests/VToken/index.test.ts
subgraphs/isolated-pools/tests/integration/pool.ts
subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
subgraphs/isolated-pools/tests/integration/vTokens.ts

This PR adds two basic optimizations to the Isolated Pools Subgraph
- uses the Bytes type for ids
- sets Transaction entity as immutable

Optimize isolated pools

---

subgraphs/protocol-reserve/schema.graphql
subgraphs/protocol-reserve/src/utilities/ids.ts
subgraphs/protocol-reserve/tests/ConverterNetwork/index.test.ts
subgraphs/protocol-reserve/tests/TokenConverter/index.test.ts
subgraphs/venus-governance/schema.graphql
subgraphs/venus-governance/src/operations/create.ts
subgraphs/venus-governance/src/operations/get.ts
subgraphs/venus-governance/src/operations/getOrCreate.ts
subgraphs/venus-governance/src/operations/update.ts
subgraphs/venus-governance/src/utilities/ids.ts
subgraphs/venus-governance/tests/integration/alpha.ts
subgraphs/venus-governance/tests/integration/bravo.ts
subgraphs/venus-governance/tests/unit/Alpha/index.test.ts
subgraphs/venus-governance/tests/unit/Bravo/index.test.ts
subgraphs/venus/schema.graphql
subgraphs/venus/src/mappings/comptroller.ts
subgraphs/venus/src/mappings/vToken.ts
subgraphs/venus/src/operations/get.ts
subgraphs/venus/src/operations/getOrCreate.ts
subgraphs/venus/src/utilities/getUnderlyingPrice.ts
subgraphs/venus/src/utilities/ids.ts
subgraphs/venus/tests/VToken/index.test.ts

Use byte as IDs
Set static entities as immutable

Subgraph optimizations

---

subgraphs/venus/schema.graphql

Add MintBehalf to Transaction enum

fix: add missing mintbehalf to enum

---

subgraphs/protocol-reserve/schema.graphql
subgraphs/protocol-reserve/src/operations/create.ts
subgraphs/protocol-reserve/src/operations/getOrCreate.ts
subgraphs/protocol-reserve/src/utilities/ids.ts
subgraphs/protocol-reserve/template-eth.yaml
subgraphs/protocol-reserve/template.yaml
subgraphs/protocol-reserve/tests/TokenConverter/index.test.ts
subgraphs/protocol-reserve/tests/TokenConverter/mocks.ts

Add asset entity to hold attributes about tokens configured on converters

feat: add Token entity to add attributes about tokens

---

subgraphs/protocol-reserve/src/operations/getOrCreate.ts

Add fix to save token on protocol reserve graph

fix: save tokens

---

subgraphs/venus/subgraph-client/index.ts
subgraphs/venus/subgraph-client/queries/accountVTokens.graphql
subgraphs/venus/tests/integration/vTokens.ts
subgraphs/venus/tests/scripts/checkAccountVTokens.ts

Add script to check indexed account vToken balances against contract

test: add script to check account vToken positions

---

subgraphs/isolated-pools/package.json
yarn.lock

Merge main into develop to prepare for release

Merge down main

---

subgraphs/isolated-pools/package.json
subgraphs/isolated-pools/src/mappings/vToken.ts
subgraphs/isolated-pools/src/operations/getOrCreate.ts
subgraphs/isolated-pools/src/operations/recordLiquidatorAsSupplier.ts
subgraphs/isolated-pools/src/operations/update.ts
subgraphs/isolated-pools/src/operations/updateOrCreate.ts
subgraphs/isolated-pools/subgraph-client/index.ts
subgraphs/isolated-pools/template.yaml
subgraphs/isolated-pools/tests/Pool/index.test.ts
subgraphs/isolated-pools/tests/VToken/index.test.ts
subgraphs/isolated-pools/tests/VToken/mocks.ts
subgraphs/isolated-pools/tests/integration/vTokens.ts
subgraphs/venus/src/mappings/vToken.ts
subgraphs/venus/src/operations/recordLiquidatorAsSupplier.ts
subgraphs/venus/tests/VToken/mocks.ts
subgraphs/venus/tests/integration/vTokens.ts

Record Liquidation Seize events to liquidators receiving vTokens are counted as suppliers

feat: handle liquidation seize events

---

subgraphs/isolated-pools/config/index.ts
subgraphs/isolated-pools/package.json

Bump Isolated Pool Version and update zksync deployment details

chore: bump isolated pools deployed version

---

subgraphs/venus-governance/src/mappings/alpha.ts
subgraphs/venus-governance/src/operations/get.ts
subgraphs/venus-governance/template.yaml
subgraphs/venus-governance/tests/common/mocks.ts
subgraphs/venus-governance/tests/unit/Alpha/index.test.ts
subgraphs/venus-governance/tests/unit/Bravo/index.test.ts
subgraphs/venus-governance/tests/unit/XVSVault/index.test.ts
subgraphs/venus/src/mappings/comptroller.ts
subgraphs/venus/src/operations/get.ts
subgraphs/venus/src/operations/getOrCreate.ts
subgraphs/venus/src/operations/updateXvsBorrowState.ts
subgraphs/venus/src/operations/updateXvsSupplyState.ts
subgraphs/venus/src/utilities/getTokenPriceCents.ts
subgraphs/venus/src/utilities/ids.ts
subgraphs/venus/template.yaml
subgraphs/venus/tests/Comptroller.test.ts
subgraphs/venus/tests/VToken/index.test.ts
subgraphs/venus/tests/VToken/mocks.ts
subgraphs/venus/tests/constants.ts
subgraphs/venus/tests/mocks.ts

Remove extra comptroller calls 
refactor initialization of comptroller entity to use a once handler

Remove extra comptroller calls and use once handler

---

subgraphs/cross-chain-governance/package.json
subgraphs/cross-chain-governance/src/operations/create.ts
subgraphs/cross-chain-governance/tests/Executor/index.test.ts

Bump cross chain governance version

chore: bump version

---

package.json
subgraphs/cross-chain-governance/package.json
subgraphs/isolated-pools/package.json
subgraphs/protocol-reserve/package.json
subgraphs/venus-governance/package.json
yarn.lock

Bump graph CLI version. Brings all packages up to the same version

chore: bump graph cli

---

subgraphs/venus-governance/schema.graphql

Update proposal state doc string

docs: update transaction state doc strings

---

subgraphs/etherfi-promo/config/index.ts
subgraphs/etherfi-promo/package.json

Deploy Etherfi promo subgraph to Arbitrum

feat: deploy etherfi promo to arbitrum

---

subgraphs/etherfi-promo/schema.graphql
subgraphs/etherfi-promo/src/operations/get.ts
subgraphs/etherfi-promo/src/operations/update.ts
subgraphs/etherfi-promo/src/utilities/exponentToBigDecimal.ts
subgraphs/etherfi-promo/subgraph-client/index.ts
subgraphs/etherfi-promo/tests/invariant.ts

refactor: make tvl in tokens

---

packages/venus-core-pool-abis/Comptroller.json
packages/venus-core-pool-abis/package.json
subgraphs/venus/src/mappings/comptroller.ts
subgraphs/venus/template.yaml
yarn.lock

Adds original VenusSpeed update event

Add old venus speed event

---

.github/workflows/ci.yaml
subgraphs/cross-chain-governance/.releaserc
subgraphs/cross-chain-governance/deploy.sh
subgraphs/cross-chain-governance/package.json
subgraphs/etherfi-promo/.releaserc
subgraphs/etherfi-promo/deploy.sh
subgraphs/etherfi-promo/package.json
subgraphs/etherfi-promo/prepare.sh
subgraphs/isolated-pools/.releaserc
subgraphs/isolated-pools/deploy.sh
subgraphs/isolated-pools/package.json
subgraphs/protocol-reserve/.releaserc
subgraphs/protocol-reserve/deploy.sh
subgraphs/protocol-reserve/package.json
subgraphs/venus-governance/.releaserc
subgraphs/venus-governance/deploy.sh
subgraphs/venus-governance/package.json
subgraphs/venus/.releaserc
subgraphs/venus/deploy.sh
subgraphs/venus/package.json

Add scripts to deploy when releasing a new version.
Pre-release channels go to testnet
Release versions are deployed to mainnet

Pre add ci deployments

---

.github/workflows/ci.yaml

Dont run in parallel

---

packages/isolated-pools-abis/Bep20.json
packages/utils/src/testing.ts
subgraphs/isolated-pools/schema.graphql
subgraphs/isolated-pools/src/mappings/underlying.ts
subgraphs/isolated-pools/src/operations/create.ts
subgraphs/isolated-pools/src/operations/get.ts
subgraphs/isolated-pools/template.yaml

Listen for updated implementation event

Update underlying names

---

subgraphs/venus/template.yaml

Adds declared calls for events with multiple external calls to speed up indexing

feat: add declared calls for events with multiple external calls

---

subgraphs/isolated-pools/deploy.sh
subgraphs/venus/config/index.ts
subgraphs/venus/package.json
subgraphs/venus/src/constants/addresses.ts
subgraphs/venus/src/constants/config-template
subgraphs/venus/src/operations/getOrCreate.ts
subgraphs/venus/tests/scripts/checkMarketPositions.ts

Release Core Pool subgraph listening to updated underlying implementations

Release  CorePool subgraph

---

.github/workflows/ci.yaml
subgraphs/isolated-pools/template.yaml

- Add indexer hints with `prune: never`, allowing time-travel queries to work again

feat: add indexer hints

---

subgraphs/cross-chain-governance/config/index.ts
subgraphs/cross-chain-governance/deploy.sh

- A couple of fixes to the deployment scripts related to Unichain Sepolia and ZKsync Sepolia

fix: cross chain governance deployment fixes
