VenusProtocol/subgraphs

- subgraphs/venus-governance/src/mappings/alpha.ts
- subgraphs/venus-governance/template.yaml
Governor Alpha v1 allows for voting without staking XVS. For Alpha v2 and later we through an error if a delegate hasn't been created before voting but in v1 we need to create the delegate when voting because it won't exist otherwise
> create delegate when voting for alpha v1

- subgraphs/venus-governance/src/mappings/bravo.ts
If the handlers are defined without the function keyword they can't be found when queried. This is likely due to a difference between how Assemblyscript compiles functions declared with the keyword and arrow functions
> declare handlers with function keyword

- README.md
The integration tests need to be run locally because the docker setup has a hiccup right now.
> Update readme with state of integration test setup

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
[VEN-829](https://jira.toolsfdg.net/browse/VEN-829)
[VEN-830](https://jira.toolsfdg.net/browse/VEN-830)
Removed duplicated `BigDecimals` values:
- `totalBorrows`
- `totalSupply`
Kept `BigInt` values:
- `treasuryTotalBorrowsWei` 
- `treasuryTotalSupplyWei`
Also removed `totalUnderlyingSupplied` and `totalUnderlyingBorrowed` as per Slack conversation.
> [VEN-829][VEN-830] fix: removed duplicate and unneeded values

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/template.yaml
- subgraphs/isolated-pools/tests/Pool/events.ts
- subgraphs/isolated-pools/tests/Pool/index.test.ts
- subgraphs/isolated-pools/tests/integration/pool.ts
- subgraphs/isolated-pools/tests/integration/queries/marketsQuery.graphql
VEN-844
- Event `NewSupplyCap` is now handled
- Updated `Market` schema to return its corresponding `supplyCap` value
- Added unit test for `handleNewSupplyCap`
- Added integration test for `handleNewSupplyCap`
> [VEN-844] Handling NewSupplyCap comptroller event

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/subgraph-client/index.ts
- subgraphs/isolated-pools/template.yaml
- subgraphs/isolated-pools/tests/Pool/index.test.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokens.graphql
VEN-900
Added to Market:
- liquidationThreshold
Reworked on AccountVToken:
- enteredMarket renamed to isCollateralOfUser
- vTokenBalance renamed to userSupplyBalanceWei and turned into a BigInt (from tokens to wei)
- storedBorrowBalance reanamed to userBorrowBalanceWei and turned into a BigInt (from tokens to wei)
Added new Pool/Comptroller event:
- NewLiquidationThreshold
> [VEN-900] Added new fields to Market and AccountVToken

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/integration/pool.ts
- subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokens.graphql
VEN-1057
- Renamed totalUnderlyingRedeemed to totalUnderlyingRedeemedWei
- Renamed totalUnderlyingRepaid to totalUnderlyingRepaidWei
- Adjusted calculation to return wei instead of tokens
> [VEN-1057] Turned totalUnderlyingRedeemed and totalUnderlyingRepaid into wei values

- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/get.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
Getters are for situations where we don't want to silently create an entity because if we missed the entity something went wrong. Because of this getters shouldn't fail silently, they should throw an error when they fail to get the entity so that the issue can be raised and investigated
Edit: While the above is true, taking down the subgraph may be extreme and a better choice is to log and monitor for errors. This will allow the fix to index in the background without breaking the current version. Updated getters to log an error.
> refactor: log missing errors from getters

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/mappings/rewardsDistributor.ts
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/utilities/ids.ts
- subgraphs/isolated-pools/template.yaml
- subgraphs/isolated-pools/tests/Pool/events.ts
- subgraphs/isolated-pools/tests/Pool/index.test.ts
- subgraphs/isolated-pools/tests/RewardsDistributor/events.ts
- subgraphs/isolated-pools/tests/RewardsDistributor/index.test.ts
- subgraphs/isolated-pools/tests/RewardsDistributor/mocks.ts
Add events related to reward distributions.
Added events include
- NewRewardsDistributor(indexed address)
- RewardTokenBorrowSpeedUpdated(indexed address,uint256)
- RewardTokenSupplySpeedUpdated(indexed address,uint256)
> [VEN-842] feat: add reward distributor events

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/mappings/poolRegistry.ts
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/Pool/index.test.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/VToken/mocks.ts
- subgraphs/isolated-pools/tests/integration/pool.ts
VEN-1063
Markets used to have zeroed values as defaults once created. Now when indexing the creation event we will read the needed values using smart contract calls.
> [VEN-1063] Fetching initial market values upon creation

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/tests/Pool/index.test.ts
- subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokens.graphql
Renames `isCollateralOfUser` back to `enteredMarket` to match the contract interface
> fix: rename isCollateralOfUser to match contract

- subgraphs/isolated-pools/src/constants/addresses.ts
- subgraphs/isolated-pools/tests/PoolRegistry/index.test.ts
- subgraphs/isolated-pools/tests/VToken/mocks.ts
VEN-1087
- Turned `priceOracleAddress` into `mockPriceOracleAddress`, as it was only being used during tests
- Removed `pauseGuardianAddress` as it was not being used anywhere
> [VEN-1087] Refactored priceOracleAddress and removed pauseGuardianAddress

- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/update.ts
VEN-1085
- Removed unused props from functions `updateAccountVTokenBorrow` and `updateAccountVTokenRepayBorrow`
> [VEN-1085] Removed unused props from updateAccountVTokenBorrow & updateAccountVTokenRepayBorrow

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokens.graphql
VEN-1084
- Renamed `userSupplyBalanceWei` to `accountSupplyBalanceWei`
- Renamed `userBorrowBalanceWei` to `accountBorrowBalanceWei`
> [VEN-1084] Renamed user fields to account fields in AccountVToken entity

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/integration/pool.ts
- subgraphs/isolated-pools/tests/integration/queries/marketByIdQuery.graphql
VEN-1086
- `supplyRatePerBlock` is now accessed directly
> [VEN-1086] Directly call supplyRatePerBlock

- subgraphs/isolated-pools/tests/integration/queries/marketByIdQuery.graphql
- subgraphs/isolated-pools/tests/integration/queries/marketsQuery.graphql
- subgraphs/isolated-pools/tests/integration/queries/poolsQuery.graphql
- GraphQL queries used during integration tests were outdated. This became evident now after hardhat deployment was sorted out.
> fix: fixed GraphQL documents based on new schema

- subgraphs/isolated-pools/config/testnet.json
- subgraphs/venus-governance/config/testnet.json
Testnet addresses are now in sync with latest IL deployment - https://github.com/VenusProtocol/isolated-pools/pull/168
> feat: updated IL addresses

- package.json
- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/template.yaml
- subgraphs/isolated-pools/tests/PoolRegistry/index.test.ts
- subgraphs/isolated-pools/tests/VToken/mocks.ts
- subgraphs/isolated-pools/tests/integration/poolRegistry.ts
- subgraphs/isolated-pools/tests/integration/queries/poolsQuery.graphql
- yarn.lock
- Bumped isolated-pools package to 0.0.18-develop.2
- Fixed the `RewardsDistributor` ABI reference missing from `Pool`
- Removing `maxAssets` from the subgraph, since got removed from `PoolLens`
> feat: subgraph now works with isolated pools 0.0.18-develop.2

- subgraphs/isolated-pools/src/utilities/getTokenPriceInUsd.ts
Calling `getUnderlyingPrice` can revert due to an invalid price, such as when the pyth price pusher is not working. This means that trying to read underlying prices for a market in a block where it reverts would make the subgraph stop working. This PR changes it so that we first check if the call was reverted.
- If it didn't revert, use the price returned
- If it did revert, fallback to 0
> [VEN-1179] getUnderlyingPrice now fallbacks if reverted

- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/tests/Pool/index.test.ts
- subgraphs/isolated-pools/tests/RewardsDistributor/index.test.ts
- We are now reading reward speeds for each market from the corresponding rewards distributor whenever we receive a `NewRewardsDistributor` event. This way we won't have empty values for reward speeds until `RewardTokenBorrowSpeedUpdated` and `RewardTokenSupplySpeedUpdated` are handled.
> [VEN-1170] Reward speeds get indexed when NewRewardsDistributor gets handled

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/constants/index.ts
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/src/utilities/getExchangeRateBigDecimal.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/VToken/mocks.ts
Refactors the Isolated Pools subgraph so that it doesn't assume the vToken decimal is 8 and instead queries the contract. The vToken decimal is 8 for the core pool but should be set as 18 for the isolated markets
> refactor: query vToken decimal instead of assuming it is 18

- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
Balances are updated directly when processing related events
> fix double accounting issue when updating transfers from borrowi when updating transfers from borrowing activity

- subgraphs/isolated-pools/src/operations/create.ts
- Refactored `try_getPoolByComptroller` to be `getPoolByComptroller`. No need to try it anymore since this call is not meant to silently error, previous version was meant to debug the subgraph failing to index it
> refactor: remove try from getPoolByComptroller

- subgraphs/isolated-pools/src/constants/addresses.ts
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/venus/src/mappings/vtoken.ts
- yarn.lock
When minting the from address is null so to properly ignore we should check if it came from a null address instead of from the token contract
> fix: properly ignore mint events

- .prettierignore
- subgraphs/isolated-pools/subgraph-client/index.ts
- subgraphs/isolated-pools/tests/integration/index.ts
- subgraphs/isolated-pools/tests/integration/poolRegistry.ts
- subgraphs/isolated-pools/tests/integration/setup.ts
- Deploy subgraph in separate test script
- Add error messaging logging if subgraph query fails
> Fix isolated pool integration test deploy

- package.json
- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/src/utilities/index.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/venus/package.json
- subgraphs/venus/schema.graphql
- subgraphs/venus/src/constants/index.ts
- subgraphs/venus/src/mappings/comptroller.ts
- subgraphs/venus/src/mappings/vToken.ts
- subgraphs/venus/src/operations/create.ts
- subgraphs/venus/src/utilities/ids.ts
- subgraphs/venus/template.yaml
- subgraphs/venus/tests/Comptroller.test.ts
- subgraphs/venus/tests/VToken/events.ts
- subgraphs/venus/tests/VToken/index.test.ts
- yarn.lock
Adds supply and borrower count to core subgraph
A borrowerCountAdjusted value is added that removes accounts that were liquidated with only dust left
> feat: add supply and borrower count to core pool

- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/operations/create.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/venus/schema.graphql
- subgraphs/venus/src/operations/update.ts
Convert underlying supply from vTokens to underlying so that both borrow and supply values are in underlying tokens
> refactor: save supply in underlying token mantissa

- subgraphs/venus/src/mappings/comptroller.ts
We need to add listening to both the original and updated events when we add a market
> feat: listen to updated vToken events

- subgraphs/venus/config/index.ts
Use unitroller subgraph as it is the proxy instead of the contract labeled comptroller which is the implementation
> fix: use unitroller address for core pool subgraph

- subgraphs/venus/src/operations/update.ts
- subgraphs/venus/src/utilities/getExchangeRate.ts
- subgraphs/venus/src/utilities/index.ts
- subgraphs/venus/src/utilities/valueOrNotAvailableIntIfReverted.ts
Fetching the exchange rate can potentially fail due to math errors. This PR updates so we can gracefully handle and log those errors
> fix: handle possible exchange rate math failure

- subgraphs/isolated-pools/src/operations/create.ts
The exchange rate calls can fail due to a math error. Generally this won't happen on market creation but for added safety we can make all calls for getting the exchange rate in a try_
> refactor: for added safety always try to get exchange rate

- subgraphs/venus/src/utilities/getTokenPriceCents.ts
There is an indexing error because a call to get the price failed. This could happen so we need to use a try in this case.
> fix: try get underlying price

- subgraphs/venus/src/mappings/vToken.ts
- subgraphs/venus/src/operations/getOrCreate.ts
- subgraphs/venus/src/operations/updateMarketBorrowRate.ts
- subgraphs/venus/src/operations/updateMarketCashMantissa.ts
- subgraphs/venus/src/operations/updateMarketExchangeRate.ts
- subgraphs/venus/src/operations/updateMarketRates.ts
- subgraphs/venus/src/operations/updateMarketSupplyRate.ts
- subgraphs/venus/src/operations/updateMarketTotalSupplyMantissa.ts
- subgraphs/venus/template.yaml
- subgraphs/venus/tests/VToken/events.ts
- subgraphs/venus/tests/VToken/index.test.ts
- `getOrCreate` market now only makes RPC calls when creating a market, getting a market only returns the stored data
- Added update operations for specific market fields that require RPC calls and/or calculation logic
- Reworked VToken events:
- accrueInterest now updates the market cash value from the corresponding event param. Makes RPC calls to retrieve the total reserves and the market rates
- Mint and redeem events update the total supply, cash and market rates.
- Borrow and repay events now update the market total borrows with the corresponding event param. Also updates the cash value and rates.
> feat: cleanup Core Pool subgraph RPC calls

- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/venus/package.json
- subgraphs/venus/src/mappings/vToken.ts
- subgraphs/venus/tests/VToken/index.test.ts
- yarn.lock
For Mint and reedeem it was assumed that transfer would handle but transfer also assumed mint and redeem handled the logic. This PR adds the logic for updating the accountVToken to their respective events.
> fix: Mint and Redeem account vtoken balances

- subgraphs/isolated-pools/tests/integration/pool.ts
- subgraphs/venus/schema.graphql
- subgraphs/venus/src/mappings/vToken.ts
- subgraphs/venus/src/operations/getOrCreate.ts
- subgraphs/venus/tests/VToken/index.test.ts
To avoid confusion we are removing total underlying supplied from the account entity.
Instead consumers should calculate this using the exchange rate and vToken balance.
> refactor: remove totalUnderlyingSuppliedMantissa from account

- package.json
- subgraphs/etherfi-promo/config/index.ts
- subgraphs/etherfi-promo/package.json
- subgraphs/etherfi-promo/schema.graphql
- subgraphs/etherfi-promo/src/constants/addresses.ts
- subgraphs/etherfi-promo/src/constants/config-template
- subgraphs/etherfi-promo/src/constants/index.ts
- subgraphs/etherfi-promo/src/mappings/vToken.ts
- subgraphs/etherfi-promo/src/operations/create.ts
- subgraphs/etherfi-promo/src/operations/get.ts
- subgraphs/etherfi-promo/src/operations/getOrCreate.ts
- subgraphs/etherfi-promo/src/operations/update.ts
- subgraphs/etherfi-promo/src/utilities/exponentToBigDecimal.ts
- subgraphs/etherfi-promo/src/utilities/ids.ts
- subgraphs/etherfi-promo/subgraph-client/.graphclientrc.yml
- subgraphs/etherfi-promo/subgraph-client/index.ts
- subgraphs/etherfi-promo/subgraph-client/queries/accountsQuery.graphql
- subgraphs/etherfi-promo/template.yaml
- subgraphs/etherfi-promo/tests/VToken/events.ts
- subgraphs/etherfi-promo/tests/VToken/index.test.ts
- subgraphs/etherfi-promo/tests/VToken/mocks.ts
- subgraphs/etherfi-promo/tests/invariant.ts
- yarn.lock
Add weETHs invariant support to etherfi subgraph
> feat: add weETHs invariant event indexing

- subgraphs/venus-governance/src/mappings/omnichainProposalSender.ts
Associate remote proposals when executing and storing payload
> fix: also associate when execture event received

- subgraphs/venus-governance/src/operations/createRemoteProposals.ts
Fix creation of trusted remote id by using correct type to decode value
> fix: decode layerzero id as i32

- subgraphs/venus-governance/config/index.ts
- subgraphs/venus-governance/schema.graphql
If a proposal is created with an invalid layerzero id we won't be able to save a related trusted remote so the value will be null.
This modifies the schema to support this edge case
> refactor: allow trusted remote to be null

- subgraphs/venus-governance/schema.graphql
- subgraphs/venus-governance/src/operations/createRemoteProposals.ts
Record Trusted Remote will null address and active = false if an invalid trusted remote is included on a proposal
> feat: save untrusted remote for completion and transparency

- subgraphs/etherfi-promo/template.yaml
- subgraphs/isolated-pools/template.yaml
- subgraphs/protocol-reserve/template-eth.yaml
- subgraphs/protocol-reserve/template.yaml
bump spec version to 1.2.0 and api versions to 0.0.9 on all subgraphs
> chore: bump spec and api versions

- package.json
- subgraphs/isolated-pools/package.json
- subgraphs/isolated-pools/schema.graphql
- subgraphs/isolated-pools/src/mappings/pool.ts
- subgraphs/isolated-pools/src/mappings/vToken.ts
- subgraphs/isolated-pools/src/operations/getOrCreate.ts
- subgraphs/isolated-pools/src/operations/recordLiquidatorAsSupplier.ts
- subgraphs/isolated-pools/src/operations/update.ts
- subgraphs/isolated-pools/subgraph-client/index.ts
- subgraphs/isolated-pools/tests/VToken/index.test.ts
- subgraphs/isolated-pools/tests/integration/checkEntities.ts
- subgraphs/isolated-pools/tests/integration/pool.ts
- subgraphs/isolated-pools/tests/integration/queries/accountFromMarket.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountPositions.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokenByAccount.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokenByAccountAndMarket.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokens.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokensWithBorrowByMarketId.graphql
- subgraphs/isolated-pools/tests/integration/queries/accountVTokensWithSupplyByMarketId.graphql
- subgraphs/isolated-pools/tests/integration/queries/marketByIdQuery.graphql
- subgraphs/isolated-pools/tests/integration/queries/marketsQuery.graphql
- subgraphs/isolated-pools/tests/integration/unlistMarkets.ts
- subgraphs/isolated-pools/tests/integration/vTokens.ts
- subgraphs/venus/tests/integration/vTokens.ts
- yarn.lock
- Use equals methods for comparing big numbers
- Refactor IL schema to be similar to Core Pool schema
- Refactor IL tests to be similar to Core Pool tests
> Refactor il subgraph with tests

- .github/workflows/ci.yaml
Upgrade github actions that are throwing warnings that they use node 12 and it is being deprecated
> ci: upgrade actions versions

- subgraphs/venus-governance/src/mappings/alpha.ts
- subgraphs/venus-governance/src/mappings/bravo.ts
- subgraphs/venus-governance/src/operations/create.ts
When saving a voter throw a critical error if the voter doesn't exist
> refactor: assert when voter exists when creating vote

- subgraphs/venus-governance/src/mappings/xvsVault.ts
- subgraphs/venus-governance/src/operations/getOrCreate.ts
- subgraphs/venus-governance/tests/integration/xvsVault.ts
- subgraphs/venus-governance/tests/unit/XVSVault/index.test.ts
- Set voting power to zero instead of deleting
- Update delegate count in deposit and withdraw events
> fix: update total delegate count, set balance to zero instead of deleting

- subgraphs/etherfi-promo/schema.graphql
- subgraphs/etherfi-promo/src/mappings/vToken.ts
- subgraphs/etherfi-promo/src/operations/get.ts
- subgraphs/etherfi-promo/src/operations/update.ts
- subgraphs/etherfi-promo/tests/VToken/index.test.ts
- subgraphs/etherfi-promo/tests/VToken/mocks.ts
Read underlying decimals when calculating exchange rate
> refactor: read underlying decimals to calculate exchange rate

- subgraphs/cross-chain-governance/package.json
- subgraphs/etherfi-promo/package.json
- subgraphs/isolated-pools/deploy.sh
- subgraphs/isolated-pools/package.json
- subgraphs/protocol-reserve/package.json
- subgraphs/venus-governance/package.json
- subgraphs/venus/package.json
> Add base to deploy script

- .github/workflows/ci.yaml
Semantic release is only configured to deploy on testnet and main but we can speed up getting green PRs by ignoring deployments all together on any branch but those two
> ci: skip deployments on non release branches

- subgraphs/protocol-reserve/src/mappings/tokenConverter.ts
- Some converter events in Ethereum are pointing to addresses that don't correspond to actual tokens. This is causing the subgraph to stop indexing at block 21836871. The TX with the events being avoided is: https://etherscan.io/tx/0xf497402d1f21a8ed6fb49a784c4d9ae570a9721e44cee173a0c60977f02fb104
> fix: skip indexing bad events from VIP-447
